import { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation, useParams } from 'react-router-dom';
import { ArrowLeft, RefreshCw, XCircle } from 'lucide-react';
import PaymentOptions from './PaymentOptions';
import { InvoiceData, InvoiceType } from './InvoiceGenerator';
import { addNotification } from '../utils/notificationUtils';
import type { User } from '../types';
import { tokenStorage } from '../utils/auth';

interface PaymentPageProps {
  user: User;
}

export default function PaymentPage({ user }: PaymentPageProps) {
  const navigate = useNavigate();
  const location = useLocation();
  const { bookingId } = useParams<{ bookingId: string }>(); // Get bookingId from URL

  const [booking, setBooking] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedPaymentMethod, setSelectedPaymentMethod] = useState<string>('');
  const [advancePercentage, setAdvancePercentage] = useState<number>(20); // Default advance percentage
  const [processing, setProcessing] = useState(false);
  const paymentProcessedRef = useRef(false);
  

  useEffect(() => {
    const fetchBooking = async () => {
      if (!bookingId) {
        setError("No booking ID provided.");
        setIsLoading(false);
        return;
      }
      try {
        // We assume an endpoint to get a specific booking will exist.
        // We may need to create this endpoint on the backend.
        const response = await fetch(`http://localhost:4000/api/bookings/${bookingId}`);
        if (!response.ok) {
          throw new Error('Booking not found or failed to load.');
        }
        const data = await response.json();
        setBooking(data);
      } catch (err: any) {
        setError(err.message || 'An unknown error occurred.');
        console.error("Error fetching booking:", err);
      } finally {
        setIsLoading(false);
      }
    };

    fetchBooking();
  }, [bookingId]);

  useEffect(() => {
    const locationState = location.state as any;
    if (locationState?.processPayment && booking && !paymentProcessedRef.current) {
      paymentProcessedRef.current = true;
      const method = locationState.paymentMethod || localStorage.getItem('pendingPaymentMethod');
      const percentage = locationState.advancePercentage || localStorage.getItem('pendingAdvancePercentage');
      if (method) {
        setSelectedPaymentMethod(method);
        if (percentage) setAdvancePercentage(typeof percentage === 'string' ? parseInt(percentage) : percentage);
        localStorage.removeItem('pendingPaymentMethod');
        localStorage.removeItem('pendingAdvancePercentage');
        handlePaymentProcessing(method, percentage);
      }
    }
  }, [booking, location.state]);

  const getPaidAmount = (method: string, percentage?: number) => {
    if (!booking) return 0;
    if (method === 'full-online') return booking.price;
    if (method === 'advance-balance') return Math.round(booking.price * ((percentage || advancePercentage) / 100));
    return 0;
  };

  const getPaymentDetails = (method: string, percentage?: number) => {
    const paidAmount = getPaidAmount(method, percentage);
    const balanceAmount = booking.price - paidAmount;

    let status: 'PAID' | 'PARTIAL' | 'SENT';
    if (method === 'full-online') {
      status = 'PAID';
    } else if (method === 'advance-balance') {
      status = 'PARTIAL';
    } else { // For 'cod' and 'pay-after-completion'
      status = 'SENT';
    }

    const paymentMethodName = {
      'full-online': 'Online Payment (Full)',
      'advance-balance': `Advance Payment (${percentage || advancePercentage}%)`,
      'cod': 'Cash on Delivery',
      'pay-after-completion': 'Online Payment After Completion'
    }[method] || 'Not Selected';

    const invoiceType: InvoiceType = {
      'full-online': 'FULL',
      'advance-balance': 'ADVANCE',
      'cod': 'COD',
      'pay-after-completion': 'FULL'
    }[method] as any || 'FULL';

    return { paidAmount, balanceAmount, status, paymentMethodName, invoiceType };
  };

  const createInvoice = (bookingData: any, paymentDetails: any): InvoiceData => {
    const now = new Date();
    return {
      invoiceNumber: '', // This will be generated by the backend
      invoiceType: paymentDetails.invoiceType,
      date: now.toLocaleDateString(),
      time: now.toLocaleTimeString(),
      bookingId: bookingData.bookingId,
      customer: { name: user.name, email: user.email, phone: user.phone || '+94 XXX XXX XXX', address: bookingData.address || 'N/A' },
      // IMPORTANT: The service name is derived from `bookingData.serviceType`.
      // If this is missing from the `currentBooking` in localStorage, the service name will be incorrect.
      service: {
        name: bookingData.serviceType || 'Cleaning Service',
        date: bookingData.date,
        time: bookingData.time,
        items: [{ name: bookingData.serviceType || 'Cleaning Service', price: bookingData.price, quantity: 1 }],
      },
      pricing: {
        subtotal: bookingData.price,
        total: bookingData.price,
        paidAmount: paymentDetails.paidAmount,
        balanceAmount: paymentDetails.balanceAmount,
      },
      paymentMethod: paymentDetails.paymentMethodName,
      // The status now comes directly from getPaymentDetails and is ready for the backend
      status: paymentDetails.status,
    };
  };

const API_BASE_URL = 'http://localhost:4000/api';

// This function transforms the frontend invoice data into the format our backend expects.
//
// FIX: This was sending flat top-level fields (subTotal, totalAmount,
// paidAmount, balanceAmount) but the createInvoice controller destructures
// req.body.pricing and req.body.payment as nested objects — it checks
// `if (!pricing)` first thing, which was always true since no `pricing`
// key existed in the old payload at all. That's why every COD/cash
// booking confirmation failed with "Missing required fields." regardless
// of what data was actually filled in.
const transformInvoiceForBackend = (invoiceData: InvoiceData, user: User): any => {
  const customerPayload: any = {
    name: invoiceData.customer.name,
    email: invoiceData.customer.email,
    phone: invoiceData.customer.phone,
    address: invoiceData.customer.address,
  };

  // Only include Mongo ObjectId userId when valid; otherwise omit to avoid Mongoose cast errors.
  if (user?.id && /^[0-9a-fA-F]{24}$/.test(user.id)) {
    customerPayload.userId = user.id;
  }

  return {
    invoiceType: invoiceData.invoiceType.toUpperCase(),
    bookingId: invoiceData.bookingId,
    customer: customerPayload,
    serviceItems: [
      {
        name: invoiceData.service.name,
        price: invoiceData.pricing.subtotal,
        quantity: 1,
      },
    ],
    customizationItems: [],
    pricing: {
      basePrice: invoiceData.pricing.total,
      discount: 0,
    },
    payment: {
      paidAmount: invoiceData.pricing.paidAmount,
      status: invoiceData.status,
      method: invoiceData.paymentMethod,
    },
    serviceDate: invoiceData.service.date,
    serviceTime: invoiceData.service.time,
    serviceAddress: invoiceData.customer.address,
    createdByStaff: user?.id || 'system',
  };
};

  const processPaymentCompletion = async (method: string, percentage: any, paymentDetails: any) => {
    const completedBooking = { ...booking, paymentMethod: method, ...paymentDetails, bookingDate: new Date().toISOString() };
    
    // 1. Create the invoice object for the frontend
    const invoiceData = createInvoice(completedBooking, paymentDetails);
    
    // 2. Transform the invoice data for the backend
    const backendInvoicePayload = transformInvoiceForBackend(invoiceData, user);

    try {
      // FIX: POST /api/invoices is auth-protected on the backend, but this
      // call had no Authorization header at all — every COD/cash booking
      // confirmation always failed with 401 Unauthorized.
      const tokens = tokenStorage.getTokens();
      const headers: HeadersInit = {
        'Content-Type': 'application/json',
        ...(tokens?.accessToken ? { Authorization: `Bearer ${tokens.accessToken}` } : {}),
      };

      // 3. Send the invoice to the backend
      const response = await fetch(`${API_BASE_URL}/invoices`, {
        method: 'POST',
        headers,
        body: JSON.stringify(backendInvoicePayload),
      });

      if (!response.ok) {
        const errorData = await response.json();
        // If the backend fails, we stop everything.
        console.error('Failed to save invoice to backend:', errorData.msg || 'Unknown error');
        // Here you might want to show an error message to the user
        return; 
      }
      
      const savedInvoice = await response.json();

      // 4. Send notifications (only after invoice is saved)
      await addNotification({
          userId: user.id,
          type: 'order-confirmed',
          title: 'Booking Confirmed! 🎉',
          message: `Your ${booking.serviceType} service is scheduled for ${booking.date} at ${booking.time}. Booking ID: ${booking.bookingId}`,
          bookingId: booking.bookingId
        });
        if (paymentDetails.paidAmount > 0) {
          await addNotification({
            userId: user.id,
            type: 'payment',
            title: 'Payment Received',
            message: `Payment of Rs. ${paymentDetails.paidAmount.toLocaleString()} received successfully.${paymentDetails.balanceAmount > 0 ? ` Balance Rs. ${paymentDetails.balanceAmount.toLocaleString()} due after service.` : ''}`,
            bookingId: booking.bookingId
          });
        }

      // 5. Clean up and navigate
      localStorage.removeItem('currentBooking');
      
      // We now pass the invoice data we received back from the server to the next page
      const navigationState = { state: { booking: completedBooking, invoice: savedInvoice, paymentMethod: method } };
      
      if (method === 'cod' || method === 'pay-after-completion') {
        navigate('/billing/booking-success', navigationState);
      } else {
        navigate('/billing/payment-success', navigationState);
      }
    } catch (error) {
      console.error('An error occurred during payment completion:', error);
      // Handle network errors or other unexpected issues
    }
  };

  const handlePaymentMethodSelect = (method: string, percentage?: number) => {
    setSelectedPaymentMethod(method);
    if (percentage) setAdvancePercentage(percentage);

    // For online payments, redirect to the payment gateway.
    if (method === 'full-online' || method === 'advance-balance') {
      if (!booking) return;
      const amount = getPaidAmount(method, percentage);
      localStorage.setItem('pendingPaymentMethod', method);
      if (percentage) localStorage.setItem('pendingAdvancePercentage', percentage.toString());

      // Redirect to the payment gateway route which handles PayHere redirection.
      // Include bookingId in the path so PaymentGatewayPage picks it up from useParams().
      window.location.href = `/payment-gateway/${encodeURIComponent(booking.bookingId)}?paymentMethod=${encodeURIComponent(method)}&amount=${encodeURIComponent(String(amount))}&advancePercentage=${encodeURIComponent(String(percentage || ''))}`;
    }
    // For offline payments, we now wait for the user to click the 'Confirm Booking' button.
    // The 'handlePaymentProcessing' function is called by that button's onClick handler.
  };

  const handlePaymentProcessing = (method: string, percentage?: number) => {
    setProcessing(true);
    const paymentDetails = getPaymentDetails(method, percentage);
    setTimeout(async () => {
      await processPaymentCompletion(method, percentage, paymentDetails);
      setProcessing(false);
    }, 2000);
  };

  if (isLoading) {
    return (
      <div className="p-8 text-center flex flex-col items-center justify-center min-h-screen">
        <RefreshCw className="w-12 h-12 text-gray-300 mx-auto mb-4 animate-spin" />
        <p className="text-gray-500 font-medium">Loading booking details...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8 text-center flex flex-col items-center justify-center min-h-screen">
        <XCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
        <p className="text-red-700 font-semibold">Error Loading Booking</p>
        <p className="text-red-600 text-sm mt-1">{error}</p>
        <button onClick={() => navigate('/services')} className="mt-6 px-4 py-2 bg-purple-600 text-white rounded-lg">
          Back to Services
        </button>
      </div>
    );
  }

  if (!booking) return null; // Should be covered by the states above

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-purple-600 hover:text-purple-700 mb-6"><ArrowLeft className="w-5 h-5" />Back</button>
          <h1 className="text-4xl font-bold mb-2">Complete Your Booking</h1>
          <p className="mb-8 text-gray-600">Choose your preferred payment method to confirm your booking</p>
          <PaymentOptions totalAmount={booking.price} serviceDetails={{ serviceName: booking.serviceType || 'Cleaning Service', customizations: [] }} onPaymentMethodSelect={handlePaymentMethodSelect} advancePercentage={advancePercentage} />
          {selectedPaymentMethod && (selectedPaymentMethod === 'cod' || selectedPaymentMethod === 'pay-after-completion') && (
            <div className="mt-6">
              <button onClick={() => handlePaymentProcessing(selectedPaymentMethod)} disabled={processing} className={`w-full py-4 rounded-lg text-lg font-semibold transition-colors ${processing ? 'bg-purple-400 cursor-not-allowed' : 'bg-purple-600 hover:bg-purple-700'} text-white`}>
                {processing ? <span className="flex items-center justify-center gap-2"><div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />Processing...</span> : 'Confirm Booking'}
              </button>
              <p className="text-xs mt-3 text-center text-gray-500">By confirming, you agree to our terms and conditions</p>
            </div>
          )}
          
        </div>
      </div>
    </div>
  );
}